version: "3.8"

services:
  fastapi:
    container_name: service_a
    expose:
      - 8000
    build: ./app
    depends_on:
      - postgres
    env_file:
      - app/app/.env
    command: bash -c "
      alembic upgrade head &&
      gunicorn -k uvicorn.workers.UvicornWorker app.main:app -b 0.0.0.0:8000"

  postgres:
    image: postgres:15.2
    expose:
      - 5432
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
      - ./backups:/backups
    env_file:
      - app/app/.env

  nginx:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - fastapi
