version: "3.8"

services:

  postgres:
    image: postgres:15.2
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./postgres/log:/etc/postgresql/log
    env_file:
      - app/app/.env
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]

