"""initial

Revision ID: beb0a35e4a6d
Revises: 
Create Date: 2024-01-03 17:47:36.484194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beb0a35e4a6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('studentprogress',
    sa.Column('current_unit_id', sa.Uuid(), nullable=False, comment='id элемента курса, на котором остановился студент'),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['current_unit_id'], ['unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_studentprogress_current_unit_id'), 'studentprogress', ['current_unit_id'], unique=False)
    op.create_index(op.f('ix_studentprogress_student_id'), 'studentprogress', ['student_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_studentprogress_student_id'), table_name='studentprogress')
    op.drop_index(op.f('ix_studentprogress_current_unit_id'), table_name='studentprogress')
    op.drop_table('studentprogress')
    op.drop_table('unit')
    # ### end Alembic commands ###
