"""add_assessments

Revision ID: eb8bad3ce9c5
Revises: 372c34d9cbb3
Create Date: 2024-01-04 16:44:46.479520

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eb8bad3ce9c5'
down_revision = '372c34d9cbb3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institution',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessment',
    sa.Column('unit_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('grade >= 0 and grade <= 100', name='grade_range'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_student_id'), 'assessment', ['student_id'], unique=True)
    op.drop_index('ix_studentprogress_student_id', table_name='studentprogress')
    op.drop_table('studentprogress')
    op.add_column('student', sa.Column('institution_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'student', 'institution', ['institution_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.drop_column('student', 'institution_id')
    op.create_table('studentprogress',
    sa.Column('current_unit_id', sa.UUID(), autoincrement=False, nullable=False, comment='id элемента курса, на котором остановился студент'),
    sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['current_unit_id'], ['unit.id'], name='studentprogress_current_unit_id_fkey'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name='studentprogress_student_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='studentprogress_pkey')
    )
    op.create_index('ix_studentprogress_student_id', 'studentprogress', ['student_id'], unique=True)
    op.drop_index(op.f('ix_assessment_student_id'), table_name='assessment')
    op.drop_table('assessment')
    op.drop_table('institution')
    # ### end Alembic commands ###
