"""fix_unique_constraint

Revision ID: 5c3ea691c286
Revises: eb8bad3ce9c5
Create Date: 2024-01-06 13:13:49.112815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c3ea691c286'
down_revision = 'eb8bad3ce9c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_assessment_student_id', table_name='assessment')
    op.create_unique_constraint('unique_assessment_for_student_and_unit', 'assessment', ['student_id', 'unit_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_assessment_for_student_and_unit', 'assessment', type_='unique')
    op.create_index('ix_assessment_student_id', 'assessment', ['student_id'], unique=True)
    # ### end Alembic commands ###
