"""add_indices_on_fks

Revision ID: 1285cb233098
Revises: 5c3ea691c286
Create Date: 2024-11-14 19:38:52.468052

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1285cb233098"
down_revision = "5c3ea691c286"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_assessment_student_id"), "assessment", ["student_id"], unique=False
    )
    op.create_index(
        op.f("ix_assessment_unit_id"), "assessment", ["unit_id"], unique=False
    )
    op.create_index(
        op.f("ix_student_institution_id"), "student", ["institution_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_student_institution_id"), table_name="student")
    op.drop_index(op.f("ix_assessment_unit_id"), table_name="assessment")
    op.drop_index(op.f("ix_assessment_student_id"), table_name="assessment")
    # ### end Alembic commands ###
