"""add_student

Revision ID: 372c34d9cbb3
Revises: beb0a35e4a6d
Create Date: 2024-01-03 18:24:55.040782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '372c34d9cbb3'
down_revision = 'beb0a35e4a6d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('name', sa.String(length=63), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_studentprogress_current_unit_id', table_name='studentprogress')
    op.create_foreign_key(None, 'studentprogress', 'student', ['student_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'studentprogress', type_='foreignkey')
    op.create_index('ix_studentprogress_current_unit_id', 'studentprogress', ['current_unit_id'], unique=False)
    op.drop_table('student')
    # ### end Alembic commands ###
