"""add_assessment_fdw_models

Revision ID: a478a2ce5c59
Revises: 1285cb233098
Create Date: 2024-11-18 20:45:30.133001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a478a2ce5c59'
down_revision = '1285cb233098'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessmentfdwthreeservices',
    sa.Column('unit_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('grade >= 0 and grade <= 100', name='grade_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'unit_id', name='unique_assessment_three_fdw_for_student_and_unit')
    )
    op.create_index(op.f('ix_assessmentfdwthreeservices_student_id'), 'assessmentfdwthreeservices', ['student_id'], unique=False)
    op.create_index(op.f('ix_assessmentfdwthreeservices_unit_id'), 'assessmentfdwthreeservices', ['unit_id'], unique=False)
    op.create_table('assessmentfdwtwoservices',
    sa.Column('unit_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('grade >= 0 and grade <= 100', name='grade_range'),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'unit_id', name='unique_assessment_two_fdw_for_student_and_unit')
    )
    op.create_index(op.f('ix_assessmentfdwtwoservices_student_id'), 'assessmentfdwtwoservices', ['student_id'], unique=False)
    op.create_index(op.f('ix_assessmentfdwtwoservices_unit_id'), 'assessmentfdwtwoservices', ['unit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessmentfdwtwoservices_unit_id'), table_name='assessmentfdwtwoservices')
    op.drop_index(op.f('ix_assessmentfdwtwoservices_student_id'), table_name='assessmentfdwtwoservices')
    op.drop_table('assessmentfdwtwoservices')
    op.drop_index(op.f('ix_assessmentfdwthreeservices_unit_id'), table_name='assessmentfdwthreeservices')
    op.drop_index(op.f('ix_assessmentfdwthreeservices_student_id'), table_name='assessmentfdwthreeservices')
    op.drop_table('assessmentfdwthreeservices')
    # ### end Alembic commands ###
